export const UserRole = {
  FARMER: "FARMER",
  BROKER: "BROKER",
  BUYER: "BUYER",
  RESELLER: "RESELLER",
  SELLER: "SELLER",
  TRADER: "TRADER",
  SHELLER_MILLER_PROCESSOR: "SHELLER_MILLER_PROCESSOR",
  EXPORTER: "EXPORTER",
  STOCK_INVESTOR: "STOCK_INVESTOR",
};

export const ProductCategory = {
  CEREALS: "CEREALS",
  PULSES: "PULSES",
  VEGETABLES: "VEGETABLES",
  FRUITS: "FRUITS",
  SPICES: "SPICES",
  OILSEEDS: "OILSEEDS",
  COTTON: "COTTON",
  SUGARCANE: "SUGARCANE",
  OTHER: "OTHER",
};
